name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # The logic below handles the NPM publication
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: bun install
        if: ${{ steps.release.outputs.release_created }}

      - name: Build SDK
        run: bun run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd packages/sdk
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
